
version: 0.2

phases:
  build:
    commands:
      - echo "Running integration test against DEV..."
      - curl -f http://3.239.122.41:5000/health

  post_build:
    commands:
      - echo "Integration test completed successfully"
